# Generated by Django 5.0.5 on 2024-05-21 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deepForestNN', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='processed_image',
        ),
        migrations.DeleteModel(
            name='Image_data',
        ),
    ]
