# Generated by Django 5.0.5 on 2024-05-21 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepForestNN', '0002_remove_user_processed_image_delete_image_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.FileField(upload_to='analyzing_images/source_images', verbose_name='Изначальное фото')),
                ('result_file', models.FileField(upload_to='analyzing_images/result_images', verbose_name='Обработанное фото')),
            ],
            options={
                'verbose_name': 'Данные по фото',
                'verbose_name_plural': 'Данные по фото',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='processed_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='deepForestNN.image_data'),
        ),
    ]
