# Generated by Django 5.0.5 on 2024-05-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepForestNN', '0003_image_data_user_processed_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_data',
            name='trees_count',
            field=models.IntegerField(default=0, verbose_name='Деревьев обнаружено'),
        ),
    ]
